// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7x7IzuSZib7L4zw6qz3G29cWSuactY0',
    appId: '1:463834872260:web:05de355e0abbe04f410c91',
    messagingSenderId: '463834872260',
    projectId: 'todoapp-ab7b7',
    authDomain: 'todoapp-ab7b7.firebaseapp.com',
    storageBucket: 'todoapp-ab7b7.appspot.com',
    measurementId: 'G-SZLNT89ZW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLmBEhBlkbX59VhP37WZ0bWScKGO7Rwk',
    appId: '1:463834872260:android:959fba252049b4ca410c91',
    messagingSenderId: '463834872260',
    projectId: 'todoapp-ab7b7',
    storageBucket: 'todoapp-ab7b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHCL7mRnbL7pvOZ9vJmodma9okab3BEk',
    appId: '1:463834872260:ios:b4fd338ea02c2cdc410c91',
    messagingSenderId: '463834872260',
    projectId: 'todoapp-ab7b7',
    storageBucket: 'todoapp-ab7b7.appspot.com',
    iosClientId: '463834872260-9r2dgeejh64bdjq546nq0u2s450enao4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHCL7mRnbL7pvOZ9vJmodma9okab3BEk',
    appId: '1:463834872260:ios:52ca9e2e78be54fa410c91',
    messagingSenderId: '463834872260',
    projectId: 'todoapp-ab7b7',
    storageBucket: 'todoapp-ab7b7.appspot.com',
    iosClientId: '463834872260-a685mhutathvl6o048885cnksq6cnrpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
